spring:
  application:
    name: api-profile
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: localhost
      port: 8510
      config:
        enabled: true
        prefix: my-network
        defaultContext: '${spring.application.name}'
